Back to original script =)

diff --git a/modules/unicorn/templates/init.sh.erb b/modules/unicorn/templates/init.sh.erb
--- a/modules/unicorn/templates/init.sh.erb
+++ b/modules/unicorn/templates/init.sh.erb
@@ -1,33 +1,24 @@
-#! /bin/sh
+#!/bin/sh
+set -e
 
-### BEGIN INIT INFO
-# Provides:          unicorn
-# Required-Start:    $all
-# Required-Stop:     $network $local_fs $syslog
-# Default-Start:     2 3 4 5
-# Default-Stop:      0 1 6
-# Short-Description: starts the unicorn web server
-# Description:       starts unicorn
-### END INIT INFO
+# Example init script, this can be used with nginx, too,
+# since nginx and unicorn accept the same signals
+USER_HOME=<%= scope.lookupvar('deployer::home') %>
+BUNDLE=$USER_HOME/.rbenv/shims/bundle
 
-# Change these to match your app:
-USER=<%= scope.lookupvar('deployer::home') %>
-APP_NAME=<%= @fqdn %>
+TIMEOUT=${TIMEOUT-60}
 APP_ROOT=<%= scope.lookupvar('vars::apps_root') %>/<%= @fqdn %>/current
+PID=/tmp/unicorn.pid
 ENV=<%= @virtual == 'virtualbox' ? 'sandbox' : 'production' %>
-RBENV_RUBY_VERSION=<%= scope.lookupvar('rbenv::ruby_version') %>
+CMD="cd $APP_ROOT; $BUNDLE exec $APP_ROOT/bin/unicorn -D -c $APP_ROOT/config/unicorn.rb -E $ENV"
 
-# env
-RBENV_ROOT="/home/$USER/.rbenv"
-PATH="$RBENV_ROOT/bin:$RBENV_ROOT/shims:$PATH"
-SET_PATH="cd $APP_ROOT; rbenv rehash; rbenv local $RBENV_RUBY_VERSION"
-DAEMON="bundle exec unicorn_rails"
-DAEMON_OPTS="-c $APP_ROOT/config/unicorn.rb -E $ENV -D"
-CMD="$SET_PATH; $DAEMON $DAEMON_OPTS"
-NAME=unicorn
-DESC="Unicorn app for $APP_NAME"
-PID="/tmp/unicorn.pid"
-OLD_PID="$PID.oldbin"
+action="$1"
+
+set -u
+
+old_pid="$PID.oldbin"
+
+<%- run_cmd = "su -c \"$CMD\" - #{scope.lookupvar('deployer::user')}" %>
 
 cd $APP_ROOT || exit 1
 
@@ -36,40 +27,52 @@ sig () {
 }
 
 oldsig () {
-  test -s $OLD_PID && kill -$1 `cat $OLD_PID`
+  test -s $old_pid && kill -$1 `cat $old_pid`
 }
 
-case ${1-help} in
-  start)
-    sig 0 && echo >&2 "Already running" && exit 0
-    su - $USER -c "$CMD"
-    ;;
-  stop)
-    sig QUIT && exit 0
-    echo >&2 "Not running"
-    ;;
-  force-stop)
-    sig TERM && exit 0
-    echo >&2 "Not running"
-    ;;
-  restart|reload)
-    sig HUP && echo reloaded OK && exit 0
-    echo >&2 "Couldn't reload, starting '$CMD' instead"
-    su - $USER -c "$CMD"
-    ;;
-  upgrade)
-    sig USR2 && exit 0
-    echo >&2 "Couldn't upgrade, starting '$CMD' instead"
-    su - $USER -c "$CMD"
-    ;;
-  rotate)
-    sig USR1 && echo rotated logs OK && exit 0
-    echo >&2 "Couldn't rotate logs" && exit 1
-    ;;
-  *)
-    echo >&2 "Usage: $0 <start|stop|restart|upgrade|rotate|force-stop>"
-    exit 1
-    ;;
-esac
+case $action in
+start)
+  sig 0 && echo >&2 "Already running" && exit 0
+  <%= run_cmd %>
+  ;;
+stop)
+  sig QUIT && exit 0
+  echo >&2 "Not running"
+  ;;
+force-stop)
+  sig TERM && exit 0
+  echo >&2 "Not running"
+  ;;
+restart|reload)
+  sig HUP && echo reloaded OK && exit 0
+  echo >&2 "Couldn't reload, starting '$CMD' instead"
+  <%= run_cmd %>
+  ;;
+upgrade)
+  if sig USR2 && sleep 2 && sig 0 && oldsig QUIT
+  then
+    n=$TIMEOUT
+    while test -s $old_pid && test $n -ge 0
+    do
+      printf '.' && sleep 1 && n=$(( $n - 1 ))
+    done
+    echo
 
-exit 0
+    if test $n -lt 0 && test -s $old_pid
+    then
+      echo >&2 "$old_pid still exists after $TIMEOUT seconds"
+      exit 1
+    fi
+    exit 0
+  fi
+  echo >&2 "Couldn't upgrade, starting '$CMD' instead"
+  <%= run_cmd %>
+  ;;
+reopen-logs)
+  sig USR1
+  ;;
+*)
+  echo >&2 "Usage: $0 <start|stop|restart|upgrade|force-stop|reopen-logs>"
+  exit 1
+  ;;
+esac
